name: Reusable Workflows

on:
    workflow_call:
      secrets:
        k8s-kubeconfig:
          required: true
        mongodb-password:
          required: true
      inputs:
        mongo-uri:
          required: true
          type: string
        kubectl-version:
          description: Provide the required kubectl version
          default: v1.26.0
          required: true
          type: string
        k8s-manifest-direc:
          description: Direc containing the k8s manifest files
          default: kubernetes
          required: true
          type: string
        environment:
          description: Provide which environment to deploy
          default: dev
          required: true
          type: string          

jobs:
  reuse-deploy:
    environment: 
      name: ${{ inputs.environment }}
      url: https://${{ steps.set-ingress-host-address.outputs.APP_INGRESS_HOST }}
    outputs:
      APP_INGRESS_URL: ${{ steps.set-ingress-host-address.outputs.APP_INGRESS_HOST }}
    runs-on: ubuntu-latest
    steps:
        - name: Checkout the Repository
          uses: actions/checkout@v4

        - name: Setting up the kubectl env
          uses: azure/setup-kubectl@v4
          with:
            version: '${{ inputs.kubectl-version }}'

        - name: Setup kubeconfig
          uses: azure/k8s-set-context@v4
          with:
            method: kubeconfig
            kubeconfig: ${{ secrets.k8s-kubeconfig }}
    
        - name: Fetch K8s Cluster Details
          run: |
            kubectl version --short
            echo ----------------------------
            kubectl get nodes

        - name: Storing Nginx Ingress Controller Hostname as a GitHub Env Variable
          run: |
            echo "INGRESS_IP=$(kubectl -n ingress-nginx get svc ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')" >> $GITHUB_ENV
          
        - name: Replace Tokens in Manifest Files
          uses: cschleiden/replace-tokens@v1
          with:
            tokenPrefix: '_{_'
            tokenSuffix: '_}_'
            files: '["${{ inputs.k8s-manifest-direc }}*.yaml"]'
          env:
            NAMESPACE: ${{ vars.NAMESPACE }}
            REPLICAS: ${{ vars.REPLICAS }}
            IMAGE: ${{ vars.DOCKER_USERNAME }}/solar-system:${{ github.sha }}
            INGRESS_IP: ${{ env.INGRESS_IP }}

        - name: Check files
          run: |
            cat ${{ inputs.k8s-manifest-direc }}*.yaml    

        - name: Create MongoDB Secret
          run: |
            kubectl -n ${{ vars.NAMESPACE }} create secret generic mongo-db-creds \
            --from-literal=MONGO_URI=${{ inputs.mongo-uri }} \
            --from-literal=MONGO_USERNAME=${{ vars.MONGO_USERNAME }} \
            --from-literal=MONGO_PASSWORD=${{ secrets.mongodb-password }} \
            --save-config \
            --dry-run=client \
            -o yaml | kubectl apply -f -

        - name: Deploying the application to Dev Env
          run: |
            kubectl apply -f ${{ inputs.k8s-manifest-direc }}

        - name: Application ingress host
          id: set-ingress-host-address
          run: |
            echo "APP_INGRESS_HOST=$(kubectl get ingress -n ${{ vars.NAMESPACE }} -o jsonpath="{.items[0].spec.tls[0].hosts[0]}")" >> "$GITHUB_OUTPUT"

  